compose_order := "docker compose -f docker-compose.dev.yml -f ../prod/docker-compose.yml"

dev-init:
    echo ".env" > .gitignore;
    cp -i .env-template .env;

dev-config:
    {{compose_order}} config

dev-build arg="--":
    {{compose_order}} build {{arg}}

dev-up arg="-d --build":
    {{compose_order}} up {{arg}}

dev-down:
    {{compose_order}} down